In [1]:
import json
import pandas as pd

with open("../data/bootstrap_static.json") as f:
    bootstrap = json.load(f)

In [2]:
players = pd.DataFrame(bootstrap["elements"])
teams = pd.DataFrame(bootstrap["teams"])

print(players.shape)
players.head()

(654, 109)

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,price_change_percent,...,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90
0,True,True,NaN,NaN,154561,0,0,0,0,12.1,...,1,50,3,55,4,5,1,1.0,0.67,0.0
1,True,True,NaN,NaN,109745,-1,1,-1,1,-9.9,...,18,533,66,533,66,464,52,0.0,0.00,0.0
2,True,True,NaN,NaN,437495,-1,1,-1,1,-7.6,...,20,541,67,541,67,542,61,0.0,0.00,0.0
3,True,True,NaN,NaN,226597,0,0,0,0,-52.7,...,1,54,21,59,23,10,2,1.0,0.67,7.0
4,True,True,25.0,25.0,445122,0,0,0,0,-0.2,...,3,649,214,649,214,458,163,0.0,0.00,0.0

In [3]:
players.columns.tolist()

['can_transact',
 'can_select',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'code',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'price_change_percent',
 'price_change_hourly_rate',
 'price_change_projections',
 'price_change_locked_until',
 'price_change_calibrating',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'first_name',
 'form',
 'id',
 'in_dreamteam',
 'news',
 'news_added',
 'now_cost',
 'photo',
 'points_per_game',
 'removed',
 'second_name',
 'selected_by_percent',
 'special',
 'squad_number',
 'status',
 'team',
 'team_code',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'known_name',
 'region',
 'team_join_date',
 'birth_date',
 'has_temporary_code',
 'opta_code',
 'minutes',
 'goals_scored',
 'assists',
 'clean_sheets',
 'goals_conceded',
 'own_goals',
 'penalties_saved',
 'penalties_missed',
 'yellow_cards',
 'red_cards',
 'saves',
 'bonus',
 'bps',
 'influence',
 'creativity',
 'threat',
 'ict_index',
 'clearances_blocks_interceptions',
 'recoveries',
 'tackles',
 'defensive_contribution',
 'starts',
 'expected_goals',
 'expected_assists',
 'expected_goal_involvements',
 'expected_goals_conceded',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'penalties_order',
 'penalties_text',
 'scout_risks',
 'scout_news_link',
 'influence_rank',
 'influence_rank_type',
 'creativity_rank',
 'creativity_rank_type',
 'threat_rank',
 'threat_rank_type',
 'ict_index_rank',
 'ict_index_rank_type',
 'expected_goals_per_90',
 'saves_per_90',
 'expected_assists_per_90',
 'expected_goal_involvements_per_90',
 'expected_goals_conceded_per_90',
 'goals_conceded_per_90',
 'now_cost_rank',
 'now_cost_rank_type',
 'form_rank',
 'form_rank_type',
 'points_per_game_rank',
 'points_per_game_rank_type',
 'selected_rank',
 'selected_rank_type',
 'starts_per_90',
 'clean_sheets_per_90',
 'defensive_contribution_per_90']

In [4]:
key_cols = [
    "id", "first_name", "second_name", "web_name", "team", "element_type",
    "now_cost", "total_points", "form", "points_per_game",
    "selected_by_percent", "minutes", "starts",
    "chance_of_playing_this_round", "chance_of_playing_next_round",
    "status", "news",
    "expected_goals", "expected_assists", "expected_goal_involvements",
    "ict_index", "influence", "creativity", "threat"
]

players_clean = players[key_cols]
players_clean.head(10)

,id,first_name,second_name,web_name,team,element_type,now_cost,total_points,form,points_per_game,...,chance_of_playing_next_round,status,news,expected_goals,expected_assists,expected_goal_involvements,ict_index,influence,creativity,threat
0,1,David,Raya Martín,Raya,1,1,60,15,5.0,5.0,...,NaN,a,,0.00,0.01,0.01,4.7,46.2,0.0,0.0
1,2,Kepa,Arrizabalaga Revuelta,Arrizabalaga,1,1,49,0,0.0,0.0,...,NaN,a,,0.00,0.00,0.00,0.0,0.0,0.0,0.0
2,3,Illan,Meslier,Meslier,1,1,49,0,0.0,0.0,...,NaN,a,,0.00,0.00,0.00,0.0,0.0,0.0,0.0
3,4,Gabriel,dos Santos Magalhães,Gabriel,1,2,80,15,5.0,5.0,...,NaN,a,,0.49,0.05,0.54,13.8,48.4,7.4,83.0
4,5,Jurriën,Timber,J.Timber,1,2,65,0,0.0,0.0,...,25.0,d,Groin injury - 25% chance of playing,0.00,0.00,0.00,0.0,0.0,0.0,0.0
5,6,William,Saliba,Saliba,1,2,59,0,0.0,0.0,...,0.0,i,Back injury - Unknown return date,0.00,0.00,0.00,0.0,0.0,0.0,0.0
6,7,Myles,Lewis-Skelly,Lewis-Skelly,1,3,55,8,2.7,2.7,...,NaN,a,,0.16,0.23,0.39,7.0,21.6,38.8,16.0
7,8,Riccardo,Calafiori,Calafiori,1,2,57,22,7.3,7.3,...,NaN,a,,0.54,0.58,1.12,11.8,51.6,27.3,39.0
8,9,Piero,Hincapié,Hincapie,1,2,53,2,0.7,1.0,...,NaN,a,,0.00,0.00,0.00,1.0,6.4,1.0,2.0
9,10,Benjamin,White,White,1,2,55,20,6.7,6.7,...,100.0,a,,0.18,0.29,0.47,14.1,65.4,52.2,23.0

In [5]:
teams[["id", "name", "short_name", "strength"]]

    id            name short_name strength
0    1         Arsenal        ARS     None
1    2     Aston Villa        AVL     None
2    3     Bournemouth        BOU     None
3    4       Brentford        BRE     None
4    5        Brighton        BHA     None
5    6         Chelsea        CHE     None
6    7   Coventry City        COV     None
7    8  Crystal Palace        CRY     None
8    9         Everton        EVE     None
9   10          Fulham        FUL     None
10  11       Hull City        HUL     None
11  12    Ipswich Town        IPS     None
12  13           Leeds        LEE     None
13  14       Liverpool        LIV     None
14  15        Man City        MCI     None
15  16         Man Utd        MUN     None
16  17       Newcastle        NEW     None
17  18   Nott'm Forest        NFO     None
18  19           Spurs        TOT     None
19  20      Sunderland        SUN     None

In [6]:
teams.columns.tolist()

['code',
 'draw',
 'form',
 'id',
 'loss',
 'name',
 'played',
 'points',
 'position',
 'short_name',
 'strength',
 'team_division',
 'unavailable',
 'win',
 'link_url',
 'strength_overall_home',
 'strength_overall_away',
 'strength_attack_home',
 'strength_attack_away',
 'strength_defence_home',
 'strength_defence_away',
 'pulse_id']

In [7]:
teams[["name", "strength_overall_home", "strength_overall_away",
       "strength_attack_home", "strength_attack_away",
       "strength_defence_home", "strength_defence_away"]]

,name,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away
0,Arsenal,4,5,0,0,0,0
1,Aston Villa,3,4,0,0,0,0
2,Bournemouth,3,3,0,0,0,0
3,Brentford,3,3,0,0,0,0
4,Brighton,2,3,0,0,0,0
5,Chelsea,4,4,0,0,0,0
6,Coventry City,2,2,0,0,0,0
7,Crystal Palace,3,3,0,0,0,0
8,Everton,3,3,0,0,0,0
9,Fulham,2,3,0,0,0,0
10,Hull City,2,2,0,0,0,0
11,Ipswich Town,2,2,0,0,0,0
12,Leeds,2,3,0,0,0,0
13,Liverpool,4,4,0,0,0,0
14,Man City,4,5,0,0,0,0
15,Man Utd,4,4,0,0,0,0
16,Newcastle,2,3,0,0,0,0
17,Nott'm Forest,3,3,0,0,0,0
18,Spurs,3,3,0,0,0,0
19,Sunderland,2,3,0,0,0,0